namespace AlphaVantageApi.Net.Domain.Enums
{
    public enum Function
    {
        TIME_SERIES_INTRADAY,
        TIME_SERIES_INTRADAY_EXTENDED,
        TIME_SERIES_DAILY,
        TIME_SERIES_DAILY_ADJUSTED,
        TIME_SERIES_WEEKLY,
        TIME_SERIES_WEEKLY_ADJUSTED,
        TIME_SERIES_MONTHLY,
        TIME_SERIES_MONTHLY_ADJUSTED,
        GLOBAL_QUOTE,
        SYMBOL_SEARCH,
        OVERVIEW,
        EARNINGS,
        INCOME_STATEMENT,
        BALANCE_SHEET,
        CASH_FLOW,
        LISTING_STATUS,
        EARNINGS_CALENDAR,
        IPO_CALENDAR
    }
}
